import express from "express";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";
import pg from "pg";
import XLSX from "xlsx";

const { Pool } = pg;
const __filename=fileURLToPath(import.meta.url),__dirname=path.dirname(__filename);
const app=express(),PORT=Number(process.env.PORT||3000);
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,max:10,idleTimeoutMillis:30000}):null;
app.use(express.json({limit:"12mb"}));app.use(express.static(path.join(__dirname,"public")));
const q=(text,params=[])=>pool.query(text,params),num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f,clean=(v,f="")=>String(v??f).trim();
const schema=`
CREATE TABLE IF NOT EXISTS restaurants(id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,language TEXT NOT NULL DEFAULT 'ru',currency TEXT NOT NULL DEFAULT 'UZS',created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS staff(id BIGSERIAL PRIMARY KEY,restaurant_id BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,name TEXT NOT NULL,role TEXT NOT NULL,phone TEXT,base_salary NUMERIC(12,2) NOT NULL DEFAULT 0,commission_pct NUMERIC(5,2) NOT NULL DEFAULT 0,rating NUMERIC(3,2) NOT NULL DEFAULT 5,username TEXT,password_hash TEXT,active BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS categories(id BIGSERIAL PRIMARY KEY,restaurant_id BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,name TEXT NOT NULL,type TEXT NOT NULL DEFAULT 'kitchen');
CREATE TABLE IF NOT EXISTS dishes(id BIGSERIAL PRIMARY KEY,restaurant_id BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,name TEXT NOT NULL,description TEXT,price NUMERIC(12,2) NOT NULL DEFAULT 0,cost NUMERIC(12,2) NOT NULL DEFAULT 0,image_url TEXT,rating NUMERIC(3,2) NOT NULL DEFAULT 5,active BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ingredients(id BIGSERIAL PRIMARY KEY,restaurant_id BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,name TEXT NOT NULL,unit TEXT NOT NULL,stock NUMERIC(14,3) NOT NULL DEFAULT 0,cost_per_unit NUMERIC(12,4) NOT NULL DEFAULT 0,min_stock NUMERIC(14,3) NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS recipes(id BIGSERIAL PRIMARY KEY,dish_id BIGINT NOT NULL REFERENCES dishes(id) ON DELETE CASCADE,ingredient_id BIGINT NOT NULL REFERENCES ingredients(id) ON DELETE CASCADE,quantity NUMERIC(14,4) NOT NULL,UNIQUE(dish_id,ingredient_id));
CREATE TABLE IF NOT EXISTS restaurant_tables(id BIGSERIAL PRIMARY KEY,restaurant_id BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,name TEXT NOT NULL,zone TEXT NOT NULL DEFAULT 'Основной',capacity INT NOT NULL DEFAULT 4,status TEXT NOT NULL DEFAULT 'free',service_pct NUMERIC(5,2) NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS orders(id BIGSERIAL PRIMARY KEY,restaurant_id BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,table_id BIGINT REFERENCES restaurant_tables(id) ON DELETE SET NULL,waiter_id BIGINT REFERENCES staff(id) ON DELETE SET NULL,status TEXT NOT NULL DEFAULT 'open',payment_method TEXT,total NUMERIC(12,2) NOT NULL DEFAULT 0,subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,service_pct NUMERIC(5,2) NOT NULL DEFAULT 0,service_amount NUMERIC(12,2) NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),closed_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS order_items(id BIGSERIAL PRIMARY KEY,order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,dish_id BIGINT NOT NULL REFERENCES dishes(id),quantity NUMERIC(10,2) NOT NULL,price NUMERIC(12,2) NOT NULL,split_group TEXT);
CREATE TABLE IF NOT EXISTS purchases(id BIGSERIAL PRIMARY KEY,restaurant_id BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,supplier TEXT,total NUMERIC(12,2) NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS purchase_items(id BIGSERIAL PRIMARY KEY,purchase_id BIGINT NOT NULL REFERENCES purchases(id) ON DELETE CASCADE,ingredient_id BIGINT NOT NULL REFERENCES ingredients(id),quantity NUMERIC(14,3) NOT NULL,unit_cost NUMERIC(12,4) NOT NULL);
CREATE TABLE IF NOT EXISTS stock_movements(id BIGSERIAL PRIMARY KEY,restaurant_id BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,ingredient_id BIGINT NOT NULL REFERENCES ingredients(id),type TEXT NOT NULL,quantity NUMERIC(14,3) NOT NULL,reason TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ai_memory(id BIGSERIAL PRIMARY KEY,restaurant_id BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,role TEXT NOT NULL DEFAULT 'user',content TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_orders_restaurant_created ON orders(restaurant_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_dishes_restaurant ON dishes(restaurant_id);`;
function hashPassword(password){const salt=crypto.randomBytes(16).toString("hex"),hash=crypto.scryptSync(String(password),salt,64).toString("hex");return `${salt}:${hash}`}
function verifyPassword(password,stored){if(!stored||!stored.includes(":"))return false;const [salt,hex]=stored.split(":"),a=Buffer.from(hex,"hex"),b=crypto.scryptSync(String(password),salt,64);return a.length===b.length&&crypto.timingSafeEqual(a,b)}
function sendError(res,e){console.error(e);res.status(e.status||500).json({error:e.message||"Ошибка сервера"})}
async function initDb(){if(!pool)return;await q(schema);for(const sql of ["ALTER TABLE staff ADD COLUMN IF NOT EXISTS username TEXT","ALTER TABLE staff ADD COLUMN IF NOT EXISTS password_hash TEXT","ALTER TABLE dishes ADD COLUMN IF NOT EXISTS rating NUMERIC(3,2) NOT NULL DEFAULT 5","ALTER TABLE restaurant_tables ADD COLUMN IF NOT EXISTS service_pct NUMERIC(5,2) NOT NULL DEFAULT 0","ALTER TABLE orders ADD COLUMN IF NOT EXISTS subtotal NUMERIC(12,2) NOT NULL DEFAULT 0","ALTER TABLE orders ADD COLUMN IF NOT EXISTS service_pct NUMERIC(5,2) NOT NULL DEFAULT 0","ALTER TABLE orders ADD COLUMN IF NOT EXISTS service_amount NUMERIC(12,2) NOT NULL DEFAULT 0"])await q(sql);let r=await q("SELECT id FROM restaurants ORDER BY id LIMIT 1"),id=r.rows[0]?.id;if(!id){id=(await q("INSERT INTO restaurants(name,language,currency) VALUES('RestoPro','ru','UZS') RETURNING id")).rows[0].id;const cats={};for(const [name,type] of [["Основные блюда","kitchen"],["Салаты","kitchen"],["Десерты","kitchen"],["Бар","bar"],["Напитки","bar"]])cats[name]=(await q("INSERT INTO categories(restaurant_id,name,type) VALUES($1,$2,$3) RETURNING id",[id,name,type])).rows[0].id;for(const [name,cat,price,cost,emoji,rating] of [["Лазанья","Основные блюда",78000,31000,"🍝",4.9],["Стейк Рибай","Основные блюда",149000,67000,"🥩",4.8],["Цезарь","Салаты",62000,25000,"🥗",4.7],["Лимонад","Напитки",28000,7000,"🍋",4.6],["Тирамису","Десерты",49000,18000,"🍰",4.9],["Капучино","Бар",28000,8000,"☕",4.8]])await q("INSERT INTO dishes(restaurant_id,category_id,name,description,price,cost,image_url,rating) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[id,cats[cat],name,"Фирменная позиция RestoPro",price,cost,`emoji:${emoji}`,rating]);for(let i=1;i<=12;i++)await q("INSERT INTO restaurant_tables(restaurant_id,name,zone,capacity,status,service_pct) VALUES($1,$2,$3,$4,'free',$5)",[id,`Стол ${String(i).padStart(2,"0")}`,i<=8?"Основной":"Терраса",i%3===0?6:4,i%4===0?10:0]);for(const [name,role,pct,rating,user] of [["Алина","Официант",8,4.9,"alina"],["Данияр","Официант",6,4.8,"daniyar"],["Мария","Официант",5,4.7,"maria"],["Алексей","Шеф-повар",0,4.9,"alex"]])await q("INSERT INTO staff(restaurant_id,name,role,commission_pct,rating,username,password_hash) VALUES($1,$2,$3,$4,$5,$6,$7)",[id,name,role,pct,rating,user,hashPassword("1234")]);for(const x of [["Мука","кг",42,12000,5],["Лосось","кг",12,95000,3],["Сливки","л",18,28000,4],["Кофе","кг",8,160000,2],["Сахар","кг",35,14000,5],["Говядина","кг",15,110000,3]])await q("INSERT INTO ingredients(restaurant_id,name,unit,stock,cost_per_unit,min_stock) VALUES($1,$2,$3,$4,$5,$6)",[id,...x])}}
const rid=async()=>{const r=await q("SELECT id FROM restaurants ORDER BY id LIMIT 1");return r.rows[0]?.id};
async function orderQuery(id){return q(`SELECT o.*,rt.name table_name,s.name waiter_name,COALESCE(json_agg(json_build_object('id',oi.id,'dishId',oi.dish_id,'name',d.name,'quantity',oi.quantity,'price',oi.price,'splitGroup',oi.split_group,'categoryType',c.type)) FILTER(WHERE oi.id IS NOT NULL),'[]') items FROM orders o LEFT JOIN restaurant_tables rt ON rt.id=o.table_id LEFT JOIN staff s ON s.id=o.waiter_id LEFT JOIN order_items oi ON oi.order_id=o.id LEFT JOIN dishes d ON d.id=oi.dish_id LEFT JOIN categories c ON c.id=d.category_id WHERE o.restaurant_id=$1 GROUP BY o.id,rt.name,s.name ORDER BY o.created_at DESC LIMIT 300`,[id])}
app.get("/health",async(_req,res)=>{try{if(!pool)throw new Error("DATABASE_URL не настроен");await q("SELECT 1");res.json({ok:true,database:true,service:"restopro-app",time:new Date().toISOString()})}catch(e){res.status(503).json({ok:false,database:false,error:e.message})}});
app.get("/api/bootstrap",async(_req,res)=>{try{const id=await rid();const [restaurant,categories,dishes,tables,staff,ingredients,orders]=await Promise.all([q("SELECT id,name,language,currency FROM restaurants WHERE id=$1",[id]),q("SELECT id,name,type FROM categories WHERE restaurant_id=$1 ORDER BY id",[id]),q("SELECT d.*,c.name category,c.type category_type FROM dishes d LEFT JOIN categories c ON c.id=d.category_id WHERE d.restaurant_id=$1 AND d.active ORDER BY d.id",[id]),q("SELECT rt.*,COUNT(o.id) FILTER(WHERE o.status IN('open','preparing','ready')) open_orders,COALESCE(MAX(o.total) FILTER(WHERE o.status IN('open','preparing','ready')),0) current_total FROM restaurant_tables rt LEFT JOIN orders o ON o.table_id=rt.id WHERE rt.restaurant_id=$1 GROUP BY rt.id ORDER BY rt.id",[id]),q("SELECT id,name,role,phone,base_salary,commission_pct,rating,username,active,COALESCE((SELECT SUM(total) FROM orders WHERE waiter_id=staff.id AND status='paid' AND created_at::date=CURRENT_DATE),0) today_sales FROM staff WHERE restaurant_id=$1 ORDER BY active DESC,id",[id]),q("SELECT * FROM ingredients WHERE restaurant_id=$1 ORDER BY name",[id]),orderQuery(id)]);res.json({restaurant:restaurant.rows[0],categories:categories.rows,dishes:dishes.rows,tables:tables.rows,staff:staff.rows,ingredients:ingredients.rows,orders:orders.rows})}catch(e){sendError(res,e)}});
app.get("/api/dashboard",async(_req,res)=>{try{const id=await rid();const [s,o,l,w,week]=await Promise.all([q("SELECT COALESCE(SUM(total) FILTER(WHERE status='paid' AND created_at::date=CURRENT_DATE),0) revenue,COUNT(*) FILTER(WHERE status='paid' AND created_at::date=CURRENT_DATE) orders,COALESCE(AVG(total) FILTER(WHERE status='paid' AND created_at::date=CURRENT_DATE),0) avg FROM orders WHERE restaurant_id=$1",[id]),q("SELECT COUNT(*) FROM orders WHERE restaurant_id=$1 AND status IN('open','preparing','ready')",[id]),q("SELECT COUNT(*) FROM ingredients WHERE restaurant_id=$1 AND stock<=min_stock",[id]),q("SELECT s.name,s.rating,COUNT(o.id) orders,COALESCE(SUM(o.total),0) sales FROM staff s LEFT JOIN orders o ON o.waiter_id=s.id AND o.status='paid' AND o.created_at::date=CURRENT_DATE WHERE s.restaurant_id=$1 AND s.role ILIKE '%официант%' GROUP BY s.id ORDER BY sales DESC LIMIT 5",[id]),q("SELECT to_char(d,'DD.MM') day,COALESCE(SUM(o.total),0) revenue FROM generate_series(CURRENT_DATE-6,CURRENT_DATE,'1 day') d LEFT JOIN orders o ON o.restaurant_id=$1 AND o.status='paid' AND o.created_at::date=d GROUP BY d ORDER BY d",[id])]);res.json({revenue:num(s.rows[0].revenue),orders:num(s.rows[0].orders),avgCheck:num(s.rows[0].avg),openOrders:num(o.rows[0].count),lowStock:num(l.rows[0].count),topWaiters:w.rows,week:week.rows})}catch(e){sendError(res,e)}});
app.get("/api/menu",async(_req,res)=>{try{res.json((await q("SELECT d.*,c.name category,c.type category_type FROM dishes d LEFT JOIN categories c ON c.id=d.category_id WHERE d.restaurant_id=$1 AND d.active ORDER BY d.id",[await rid()])).rows)}catch(e){sendError(res,e)}});
app.post("/api/menu",async(req,res)=>{try{const id=await rid(),name=clean(req.body.name);if(!name)return res.status(400).json({error:"Название обязательно"});const r=await q("INSERT INTO dishes(restaurant_id,category_id,name,description,price,cost,image_url,rating) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *",[id,req.body.category_id||req.body.categoryId||null,name,clean(req.body.description),num(req.body.price),num(req.body.cost),clean(req.body.imageUrl||req.body.image_url),num(req.body.rating,5)]);res.status(201).json(r.rows[0])}catch(e){sendError(res,e)}});
app.patch("/api/menu/:id",async(req,res)=>{try{const allowed={name:"name",description:"description",price:"price",cost:"cost",category_id:"category_id",rating:"rating",image_url:"image_url"},fields=[],vals=[];for(const [k,col] of Object.entries(allowed))if(req.body[k]!==undefined){fields.push(`${col}=$${vals.length+1}`);vals.push(["price","cost","category_id","rating"].includes(k)?num(req.body[k]):clean(req.body[k]))}if(!fields.length)return res.status(400).json({error:"Нет изменений"});vals.push(req.params.id,await rid());const r=await q(`UPDATE dishes SET ${fields.join(",")} WHERE id=$${vals.length-1} AND restaurant_id=$${vals.length} RETURNING *`,vals);if(!r.rowCount)return res.status(404).json({error:"Блюдо не найдено"});res.json(r.rows[0])}catch(e){sendError(res,e)}});
app.post("/api/categories",async(req,res)=>{try{const r=await q("INSERT INTO categories(restaurant_id,name,type) VALUES($1,$2,$3) RETURNING *",[await rid(),clean(req.body.name),req.body.type==="bar"?"bar":"kitchen"]);res.status(201).json(r.rows[0])}catch(e){sendError(res,e)}});
app.get("/api/tables",async(_req,res)=>{try{res.json((await q("SELECT rt.*,COUNT(o.id) FILTER(WHERE o.status IN('open','preparing','ready')) open_orders,COALESCE(MAX(o.total) FILTER(WHERE o.status IN('open','preparing','ready')),0) current_total FROM restaurant_tables rt LEFT JOIN orders o ON o.table_id=rt.id WHERE rt.restaurant_id=$1 GROUP BY rt.id ORDER BY rt.id",[await rid()])).rows)}catch(e){sendError(res,e)}});
app.post("/api/tables",async(req,res)=>{try{const r=await q("INSERT INTO restaurant_tables(restaurant_id,name,zone,capacity,status,service_pct) VALUES($1,$2,$3,$4,'free',$5) RETURNING *",[await rid(),clean(req.body.name,"Новый стол"),clean(req.body.zone,"Основной"),num(req.body.capacity,4),num(req.body.servicePct)]);res.status(201).json(r.rows[0])}catch(e){sendError(res,e)}});
app.patch("/api/tables/:id",async(req,res)=>{try{const fields=[],vals=[];for(const [k,col] of [["name","name"],["zone","zone"],["capacity","capacity"],["status","status"],["servicePct","service_pct"]])if(req.body[k]!==undefined){fields.push(`${col}=$${vals.length+1}`);vals.push(["capacity","servicePct"].includes(k)?num(req.body[k]):clean(req.body[k]))}if(!fields.length)return res.status(400).json({error:"Нет изменений"});vals.push(req.params.id,await rid());const r=await q(`UPDATE restaurant_tables SET ${fields.join(",")} WHERE id=$${vals.length-1} AND restaurant_id=$${vals.length} RETURNING *`,vals);if(!r.rowCount)return res.status(404).json({error:"Стол не найден"});res.json(r.rows[0])}catch(e){sendError(res,e)}});
app.get("/api/staff",async(_req,res)=>{try{res.json((await q("SELECT id,name,role,phone,base_salary,commission_pct,rating,username,active,COALESCE((SELECT SUM(total) FROM orders WHERE waiter_id=staff.id AND status='paid' AND created_at::date=CURRENT_DATE),0) today_sales FROM staff WHERE restaurant_id=$1 ORDER BY active DESC,id",[await rid()])).rows)}catch(e){sendError(res,e)}});
app.post("/api/staff",async(req,res)=>{try{const username=clean(req.body.username);if(!clean(req.body.name)||!username||!clean(req.body.password))return res.status(400).json({error:"Имя, логин и пароль обязательны"});const r=await q("INSERT INTO staff(restaurant_id,name,role,phone,base_salary,commission_pct,rating,username,password_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id,name,role,phone,base_salary,commission_pct,rating,username,active",[await rid(),clean(req.body.name),clean(req.body.role,"Официант"),clean(req.body.phone),num(req.body.baseSalary),num(req.body.commissionPct),num(req.body.rating,5),username,hashPassword(req.body.password)]);res.status(201).json(r.rows[0])}catch(e){sendError(res,e)}});
app.patch("/api/staff/:id",async(req,res)=>{try{const fields=[],vals=[];for(const [k,col] of [["name","name"],["role","role"],["phone","phone"],["baseSalary","base_salary"],["commissionPct","commission_pct"],["rating","rating"],["username","username"]])if(req.body[k]!==undefined){fields.push(`${col}=$${vals.length+1}`);vals.push(["baseSalary","commissionPct","rating"].includes(k)?num(req.body[k]):clean(req.body[k]))}if(req.body.password){fields.push(`password_hash=$${vals.length+1}`);vals.push(hashPassword(req.body.password))}if(!fields.length)return res.status(400).json({error:"Нет изменений"});vals.push(req.params.id,await rid());const r=await q(`UPDATE staff SET ${fields.join(",")} WHERE id=$${vals.length-1} AND restaurant_id=$${vals.length} RETURNING id,name,role,phone,base_salary,commission_pct,rating,username,active`,vals);if(!r.rowCount)return res.status(404).json({error:"Сотрудник не найден"});res.json(r.rows[0])}catch(e){sendError(res,e)}});
app.post("/api/staff/login",async(req,res)=>{try{const r=await q("SELECT id,name,role,username,password_hash,rating FROM staff WHERE restaurant_id=$1 AND username=$2 AND active",[await rid(),clean(req.body.username)]),s=r.rows[0];if(!s||!verifyPassword(req.body.password,s.password_hash))return res.status(401).json({error:"Неверный логин или пароль"});delete s.password_hash;res.json({ok:true,staff:s})}catch(e){sendError(res,e)}});
app.get("/api/orders",async(_req,res)=>{try{res.json((await orderQuery(await rid())).rows)}catch(e){sendError(res,e)}});
app.get("/api/orders/:id",async(req,res)=>{try{const r=await q(`SELECT o.*,rt.name table_name,s.name waiter_name,COALESCE(json_agg(json_build_object('id',oi.id,'dishId',oi.dish_id,'name',d.name,'quantity',oi.quantity,'price',oi.price,'splitGroup',oi.split_group,'categoryType',c.type)) FILTER(WHERE oi.id IS NOT NULL),'[]') items FROM orders o LEFT JOIN restaurant_tables rt ON rt.id=o.table_id LEFT JOIN staff s ON s.id=o.waiter_id LEFT JOIN order_items oi ON oi.order_id=o.id LEFT JOIN dishes d ON d.id=oi.dish_id LEFT JOIN categories c ON c.id=d.category_id WHERE o.restaurant_id=$1 AND o.id=$2 GROUP BY o.id,rt.name,s.name`,[await rid(),req.params.id]);if(!r.rowCount)return res.status(404).json({error:"Заказ не найден"});res.json(r.rows[0])}catch(e){sendError(res,e)}});
app.post("/api/orders",async(req,res)=>{const client=await pool.connect();try{const id=await rid(),items=Array.isArray(req.body.items)?req.body.items:[];if(!items.length)return res.status(400).json({error:"Добавьте блюда"});await client.query("BEGIN");const ids=items.map(x=>Number(x.dishId)).filter(Boolean),ds=(await client.query("SELECT d.*,c.type category_type FROM dishes d LEFT JOIN categories c ON c.id=d.category_id WHERE d.id=ANY($1::bigint[]) AND d.restaurant_id=$2",[ids,id])).rows,map=new Map(ds.map(d=>[Number(d.id),d]));let subtotal=0;const norm=items.map(x=>{const d=map.get(Number(x.dishId));if(!d)throw new Error("Блюдо не найдено");const quantity=Math.max(.01,num(x.quantity,1));subtotal+=num(d.price)*quantity;return{d,quantity}});let servicePct=0;if(req.body.tableId){const t=(await client.query("SELECT service_pct FROM restaurant_tables WHERE id=$1 AND restaurant_id=$2",[req.body.tableId,id])).rows[0];servicePct=num(t?.service_pct)}const serviceAmount=subtotal*servicePct/100,total=subtotal+serviceAmount,o=(await client.query("INSERT INTO orders(restaurant_id,table_id,waiter_id,status,subtotal,service_pct,service_amount,total) VALUES($1,$2,$3,'open',$4,$5,$6,$7) RETURNING *",[id,req.body.tableId||null,req.body.waiterId||null,subtotal,servicePct,serviceAmount,total])).rows[0];for(const x of norm)await client.query("INSERT INTO order_items(order_id,dish_id,quantity,price,split_group) VALUES($1,$2,$3,$4,'A')",[o.id,x.d.id,x.quantity,x.d.price]);if(req.body.tableId)await client.query("UPDATE restaurant_tables SET status='busy' WHERE id=$1 AND restaurant_id=$2",[req.body.tableId,id]);await client.query("COMMIT");res.status(201).json(o)}catch(e){await client.query("ROLLBACK").catch(()=>{});sendError(res,e)}finally{client.release()}});
app.patch("/api/orders/:id/status",async(req,res)=>{try{const r=await q("UPDATE orders SET status=$1 WHERE id=$2 AND restaurant_id=$3 RETURNING *",[clean(req.body.status,"open"),req.params.id,await rid()]);if(!r.rowCount)return res.status(404).json({error:"Заказ не найден"});res.json(r.rows[0])}catch(e){sendError(res,e)}});
app.post("/api/orders/:id/pay",async(req,res)=>{const client=await pool.connect();try{await client.query("BEGIN");const o=(await client.query("SELECT * FROM orders WHERE id=$1 AND restaurant_id=$2 FOR UPDATE",[req.params.id,await rid()])).rows[0];if(!o)return res.status(404).json({error:"Заказ не найден"});await client.query("UPDATE orders SET status='paid',payment_method=$1,closed_at=now() WHERE id=$2",[clean(req.body.paymentMethod,"cash"),o.id]);await client.query("UPDATE restaurant_tables SET status='free' WHERE id=$1 AND NOT EXISTS(SELECT 1 FROM orders WHERE table_id=$1 AND status IN('open','preparing','ready'))",[o.table_id]);await client.query("COMMIT");res.json({ok:true,orderId:o.id})}catch(e){await client.query("ROLLBACK").catch(()=>{});sendError(res,e)}finally{client.release()}});
app.post("/api/orders/:id/split",async(req,res)=>{try{for(const g of req.body.groups||[])for(const itemId of g.itemIds||[])await q("UPDATE order_items SET split_group=$1 WHERE id=$2 AND order_id=$3",[clean(g.name,"A"),itemId,req.params.id]);res.json({ok:true})}catch(e){sendError(res,e)}});
app.get("/api/kitchen",async(req,res)=>{try{const type=req.query.type==="bar"?"bar":"kitchen";res.json((await q(`SELECT o.id,o.status,o.created_at,rt.name table_name,s.name waiter_name,COALESCE(json_agg(json_build_object('name',d.name,'quantity',oi.quantity,'price',oi.price)) FILTER(WHERE oi.id IS NOT NULL),'[]') items FROM orders o LEFT JOIN restaurant_tables rt ON rt.id=o.table_id LEFT JOIN staff s ON s.id=o.waiter_id LEFT JOIN order_items oi ON oi.order_id=o.id LEFT JOIN dishes d ON d.id=oi.dish_id LEFT JOIN categories c ON c.id=d.category_id WHERE o.restaurant_id=$1 AND o.status IN('open','preparing','ready') AND c.type=$2 GROUP BY o.id,rt.name,s.name ORDER BY o.created_at`,[await rid(),type])).rows)}catch(e){sendError(res,e)}});
app.get("/api/stock",async(_req,res)=>{try{const id=await rid();const[i,p,m]=await Promise.all([q("SELECT * FROM ingredients WHERE restaurant_id=$1 ORDER BY name",[id]),q("SELECT * FROM purchases WHERE restaurant_id=$1 ORDER BY created_at DESC LIMIT 50",[id]),q("SELECT sm.*,i.name ingredient_name FROM stock_movements sm JOIN ingredients i ON i.id=sm.ingredient_id WHERE sm.restaurant_id=$1 ORDER BY sm.created_at DESC LIMIT 100",[id])]);res.json({ingredients:i.rows,purchases:p.rows,movements:m.rows})}catch(e){sendError(res,e)}});
app.post("/api/stock",async(req,res)=>{try{const id=await rid(),qty=num(req.body.quantity),ing=(await q("UPDATE ingredients SET stock=stock+$1 WHERE id=$2 AND restaurant_id=$3 RETURNING *",[qty,req.body.ingredientId,id])).rows[0];if(!ing)return res.status(404).json({error:"Ингредиент не найден"});await q("INSERT INTO stock_movements(restaurant_id,ingredient_id,type,quantity,reason) VALUES($1,$2,$3,$4,$5)",[id,req.body.ingredientId,clean(req.body.type,"adjustment"),qty,clean(req.body.reason)]);res.json(ing)}catch(e){sendError(res,e)}});
app.post("/api/ingredients",async(req,res)=>{try{const r=await q("INSERT INTO ingredients(restaurant_id,name,unit,stock,cost_per_unit,min_stock) VALUES($1,$2,$3,$4,$5,$6) RETURNING *",[await rid(),clean(req.body.name),clean(req.body.unit,"шт"),num(req.body.stock),num(req.body.costPerUnit),num(req.body.minStock)]);res.status(201).json(r.rows[0])}catch(e){sendError(res,e)}});
app.post("/api/purchases",async(req,res)=>{const client=await pool.connect();try{const id=await rid(),items=req.body.items||[];if(!items.length)return res.status(400).json({error:"Добавьте позиции закупки"});await client.query("BEGIN");let total=0,p=(await client.query("INSERT INTO purchases(restaurant_id,supplier,total) VALUES($1,$2,0) RETURNING *",[id,clean(req.body.supplier,"Поставщик")])).rows[0];for(const x of items){const qty=num(x.quantity),cost=num(x.unitCost);total+=qty*cost;await client.query("INSERT INTO purchase_items(purchase_id,ingredient_id,quantity,unit_cost) VALUES($1,$2,$3,$4)",[p.id,x.ingredientId,qty,cost]);await client.query("UPDATE ingredients SET stock=stock+$1,cost_per_unit=$2 WHERE id=$3 AND restaurant_id=$4",[qty,cost,x.ingredientId,id]);await client.query("INSERT INTO stock_movements(restaurant_id,ingredient_id,type,quantity,reason) VALUES($1,$2,'purchase',$3,$4)",[id,x.ingredientId,qty,clean(req.body.supplier,"Поставка")])}p=(await client.query("UPDATE purchases SET total=$1 WHERE id=$2 RETURNING *",[total,p.id])).rows[0];await client.query("COMMIT");res.status(201).json(p)}catch(e){await client.query("ROLLBACK").catch(()=>{});sendError(res,e)}finally{client.release()}});
app.get("/api/recipes",async(_req,res)=>{try{res.json((await q(`SELECT d.id dish_id,d.name dish_name,COALESCE(SUM(r.quantity*i.cost_per_unit),d.cost) cost,COALESCE(json_agg(json_build_object('ingredientId',i.id,'ingredient',i.name,'unit',i.unit,'quantity',r.quantity,'cost',r.quantity*i.cost_per_unit)) FILTER(WHERE r.id IS NOT NULL),'[]') ingredients FROM dishes d LEFT JOIN recipes r ON r.dish_id=d.id LEFT JOIN ingredients i ON i.id=r.ingredient_id WHERE d.restaurant_id=$1 GROUP BY d.id ORDER BY d.id`,[await rid()])).rows)}catch(e){sendError(res,e)}});
app.post("/api/recipes",async(req,res)=>{try{return await saveRecipe(req,res,req.body.dishId)}catch(e){sendError(res,e)}});app.put("/api/recipes/:dishId",async(req,res)=>{try{return await saveRecipe(req,res,req.params.dishId)}catch(e){sendError(res,e)}});
async function saveRecipe(req,res,dishId){const client=await pool.connect();try{const id=await rid(),ingredients=Array.isArray(req.body.ingredients)?req.body.ingredients:[];await client.query("BEGIN");const dish=(await client.query("SELECT id FROM dishes WHERE id=$1 AND restaurant_id=$2",[dishId,id])).rows[0];if(!dish){await client.query("ROLLBACK");return res.status(404).json({error:"Блюдо не найдено"})}await client.query("DELETE FROM recipes WHERE dish_id=$1",[dishId]);for(const x of ingredients){const ingredientId=Number(x.ingredientId),quantity=Math.max(0,num(x.quantity));if(ingredientId&&quantity>0)await client.query("INSERT INTO recipes(dish_id,ingredient_id,quantity) VALUES($1,$2,$3)",[dishId,ingredientId,quantity])}const cost=(await client.query("SELECT COALESCE(SUM(r.quantity*i.cost_per_unit),0) cost FROM recipes r JOIN ingredients i ON i.id=r.ingredient_id WHERE r.dish_id=$1",[dishId])).rows[0].cost;await client.query("UPDATE dishes SET cost=$1 WHERE id=$2",[cost,dishId]);await client.query("COMMIT");return res.json({ok:true,cost:num(cost)})}catch(e){await client.query("ROLLBACK").catch(()=>{});throw e}finally{client.release()}}
app.get("/api/reports",async(_req,res)=>{try{const id=await rid();const[sales,top,waiters,purchases]=await Promise.all([q("SELECT created_at::date date,COUNT(*) orders,COALESCE(SUM(total),0) revenue,COALESCE(AVG(total),0) avg FROM orders WHERE restaurant_id=$1 AND status='paid' AND created_at>=CURRENT_DATE-INTERVAL '30 days' GROUP BY created_at::date ORDER BY date",[id]),q("SELECT d.name,d.rating,SUM(oi.quantity) sales_qty,SUM(oi.quantity*oi.price) revenue,SUM(oi.quantity*(oi.price-d.cost)) margin FROM order_items oi JOIN orders o ON o.id=oi.order_id JOIN dishes d ON d.id=oi.dish_id WHERE o.restaurant_id=$1 AND o.status='paid' GROUP BY d.id ORDER BY revenue DESC LIMIT 20",[id]),q("SELECT s.name,s.rating,COUNT(o.id) orders,COALESCE(SUM(o.total),0) sales FROM staff s LEFT JOIN orders o ON o.waiter_id=s.id AND o.status='paid' WHERE s.restaurant_id=$1 AND s.role ILIKE '%официант%' GROUP BY s.id ORDER BY sales DESC",[id]),q("SELECT COALESCE(SUM(total),0) purchases FROM purchases WHERE restaurant_id=$1 AND created_at>=CURRENT_DATE-INTERVAL '30 days'",[id])]);res.json({sales:sales.rows,topDishes:top.rows,dishRatings:top.rows,waiterRatings:waiters.rows,purchases:num(purchases.rows[0].purchases)})}catch(e){sendError(res,e)}});
app.get("/api/export/xlsx",async(_req,res)=>{try{const id=await rid(),[orders,items,menu,stock,staff]=await Promise.all([q("SELECT id,created_at,status,payment_method,subtotal,service_pct,service_amount,total,table_id,waiter_id FROM orders WHERE restaurant_id=$1 ORDER BY created_at DESC",[id]),q("SELECT oi.order_id,d.name,oi.quantity,oi.price,oi.split_group FROM order_items oi JOIN dishes d ON d.id=oi.dish_id JOIN orders o ON o.id=oi.order_id WHERE o.restaurant_id=$1 ORDER BY oi.order_id DESC",[id]),q("SELECT d.id,d.name,c.name category,d.price,d.cost,d.rating FROM dishes d LEFT JOIN categories c ON c.id=d.category_id WHERE d.restaurant_id=$1 ORDER BY d.id",[id]),q("SELECT id,name,unit,stock,cost_per_unit,min_stock FROM ingredients WHERE restaurant_id=$1 ORDER BY name",[id]),q("SELECT id,name,role,phone,base_salary,commission_pct,rating,username,active FROM staff WHERE restaurant_id=$1 ORDER BY id",[id])]);const wb=XLSX.utils.book_new();for(const [n,r] of [["Orders",orders],["Order Items",items],["Menu",menu],["Stock",stock],["Staff",staff]])XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(r.rows),n);const buf=XLSX.write(wb,{type:"buffer",bookType:"xlsx"});res.setHeader("Content-Type","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");res.setHeader("Content-Disposition","attachment; filename=restopro-report.xlsx");res.send(buf)}catch(e){sendError(res,e)}});
app.post("/api/settings",async(req,res)=>{try{const id=await rid(),lang=clean(req.body.language,"ru"),cur=clean(req.body.currency,"UZS");if(!["ru","uz","en"].includes(lang)||!["UZS","USD","RUB"].includes(cur))return res.status(400).json({error:"Неверный язык или валюта"});const r=await q("UPDATE restaurants SET name=$1,language=$2,currency=$3 WHERE id=$4 RETURNING id,name,language,currency",[clean(req.body.name,"RestoPro"),lang,cur,id]);res.json(r.rows[0])}catch(e){sendError(res,e)}});
app.get("/api/integrations",async(_req,res)=>res.json({database:Boolean(pool),openai:Boolean(process.env.OPENAI_API_KEY),telegram:Boolean(process.env.TELEGRAM_BOT_TOKEN&&process.env.TELEGRAM_CHAT_ID)}));
async function telegramSend(req,res){try{const token=process.env.TELEGRAM_BOT_TOKEN,chatId=process.env.TELEGRAM_CHAT_ID;if(!token||!chatId)return res.status(503).json({error:"TELEGRAM_BOT_TOKEN и TELEGRAM_CHAT_ID не заданы"});const r=await fetch(`https://api.telegram.org/bot${token}/sendMessage`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({chat_id:chatId,text:"✅ RestoPro: Telegram интеграция работает."})}),j=await r.json();res.status(r.ok?200:502).json(j)}catch(e){sendError(res,e)}}
app.post("/api/integrations/telegram/test",telegramSend);app.post("/api/telegram/test",telegramSend);
app.get("/api/ai/memory",async(_req,res)=>{try{res.json((await q("SELECT id,role,content,created_at FROM ai_memory WHERE restaurant_id=$1 ORDER BY created_at ASC",[await rid()])).rows)}catch(e){sendError(res,e)}});
app.post("/api/ai/memory",async(req,res)=>{try{const r=await q("INSERT INTO ai_memory(restaurant_id,role,content) VALUES($1,'user',$2) RETURNING id,role,content,created_at",[await rid(),clean(req.body.content)]);res.status(201).json(r.rows[0])}catch(e){sendError(res,e)}});
app.delete("/api/ai/memory",async(_req,res)=>{try{await q("DELETE FROM ai_memory WHERE restaurant_id=$1",[await rid()]);res.json({ok:true})}catch(e){sendError(res,e)}});
app.post("/api/ai/chat",async(req,res)=>{try{const key=process.env.OPENAI_API_KEY;if(!key)return res.status(503).json({error:"Добавьте OPENAI_API_KEY в Railway Variables"});const id=await rid(),memory=(await q("SELECT role,content FROM ai_memory WHERE restaurant_id=$1 ORDER BY created_at DESC LIMIT 20",[id])).rows.reverse(),[d,o,s,i]=await Promise.all([q("SELECT name,price,cost,rating FROM dishes WHERE restaurant_id=$1",[id]),q("SELECT status,total,subtotal,service_pct,created_at FROM orders WHERE restaurant_id=$1 ORDER BY created_at DESC LIMIT 50",[id]),q("SELECT name,role,commission_pct,rating FROM staff WHERE restaurant_id=$1",[id]),q("SELECT name,stock,min_stock,cost_per_unit FROM ingredients WHERE restaurant_id=$1",[id])]);const question=clean(req.body.message);await q("INSERT INTO ai_memory(restaurant_id,role,content) VALUES($1,'user',$2)",[id,question]);const input=`Ресторан RestoPro. Отвечай по-русски, коротко и практично. Не выдумывай данные. POS: ${JSON.stringify({dishes:d.rows,orders:o.rows,staff:s.rows,stock:i.rows,memory})}. Вопрос: ${question}`;const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${key}`},body:JSON.stringify({model:process.env.OPENAI_MODEL||"gpt-5.4",instructions:"Ты AI-управляющий рестораном RestoPro. Используй только предоставленные данные и память.",input})}),j=await r.json();if(!r.ok)return res.status(r.status).json({error:j.error?.message||"OpenAI error"});const answer=j.output_text||"Нет ответа";await q("INSERT INTO ai_memory(restaurant_id,role,content) VALUES($1,'assistant',$2)",[id,answer]);res.json({answer})}catch(e){sendError(res,e)}});
app.use((req,res,next)=>{if(req.method!=="GET"||req.path.startsWith("/api/")||req.path==="/health")return next();res.sendFile(path.join(__dirname,"public","premium.html"))});
await initDb();app.listen(PORT,"0.0.0.0",()=>console.log(`RestoPro final POS running on ${PORT}`));
